POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "sefu",
    "password": "1234"
}

###
GET https://postman-echo.com/get?foo1=bar1&foo2=bar2
###

POST http://localhost:8080/login
# Content-Type: application/json

{
    "username": "sefu",
    "password": "1234"
}

###

POST http://localhost:8080/users/get?id=123
# Content-Type: application/json

# {
#     "username": "sefu",
#     "password": "12345"
# }

###
GET http://localhost:8080/users/get?id=akjsz2iiowt
Authorization: reno2z33pglio14vkfob
###

DELETE  http://localhost:8080/users/delete?id=6npi74tki85
Authorization: kwyrdftu8x9r5iope1cap
###
GET http://localhost:8080/users/getall
Authorization: 2kj43e2j0a300ygu2fxc66x
###
PUT http://localhost:8080/users/create
Authorization: reno2z33pglio14vkfob
Content-Type: application/json

{
  "age": 45,
  "email": "some@otheremail.com",
  "name": "barosanu",
  "workingPosition": 3
}
###
PUT http://localhost:8080/users/update
Authorization: reno2z33pglio14vkfob
Content-Type: application/json

{
  "age": 45,
  "id": "akjsz2iiowt",
  "email": "some@otheremail.com-UPDATED",
  "name": "barosanu",
  "workingPosition": 3
}