POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "sefu",
    "password": "1234"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "sefu",
    "password": "12345"
}

###

POST http://localhost:8080/users/get?id=123
# Content-Type: application/json

# {
#     "username": "sefu",
#     "password": "12345"
# }

###
GET http://localhost:8080/users/get?id=1233sdf
Authorization: v7ver7809jbt24uy3m9su